import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "kwality optocal",
//   description: "Generated by Akagami",
//   icons:""
// };
export const metadata: Metadata = {
  title: "Kwality Optical",
  description: "Your trusted optical service, providing quality frames and eye care since 1978.",
  icons: [
    {
      url: "/icon.png",  // Use 'url' instead of 'href'
      rel: "icon",
    },
    {
      url: "/icon.png", // iOS icon
      rel: "apple-touch-icon",
      sizes: "180x180",
    },
    {
      url: "/android.png", // Android icon
      rel: "icon",
      sizes: "192x192",
    },
  ],
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="dark" >
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        <div className="relative flex items-center w-full justify-center ">
      <Navbar/>
      </div>
        {children}
      </body>
    </html>
  );
}
